# Generated by Django 6.0.3 on 2026-04-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylog',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
