# Generated by Django 6.0.3 on 2026-04-29 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_weeklylog_feedback'),
        ('placements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='weeklylog',
            constraint=models.UniqueConstraint(fields=('student', 'week_number', 'placement'), name='unique_weekly_log'),
        ),
    ]
