# Generated by Django 5.0.1 on 2026-05-01 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Criteria Name')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight (e.g., 0.40 for 40%)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('supervisor', 'Workplace Supervisor'), ('academic', 'Academic Supervisor')], default='supervisor', max_length=50, verbose_name='Evaluator Category')),
            ],
            options={
                'verbose_name': 'Evaluation Criteria',
                'verbose_name_plural': 'Evaluation Criteria',
            },
        ),
        migrations.CreateModel(
            name='InternshipPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company / Organization')),
                ('start_date', models.DateField(verbose_name='Internship Start Date')),
                ('end_date', models.DateField(verbose_name='Internship End Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Placement Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_supervisor', models.ForeignKey(blank=True, limit_choices_to={'role': 'academic_supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_supervised_placements', to=settings.AUTH_USER_MODEL, verbose_name='Academic Supervisor')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student_intern'}, on_delete=django.db.models.deletion.CASCADE, related_name='internship_placements', to=settings.AUTH_USER_MODEL, verbose_name='Student Intern')),
                ('workplace_supervisor', models.ForeignKey(blank=True, limit_choices_to={'role': 'workplace_supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_placements', to=settings.AUTH_USER_MODEL, verbose_name='Workplace Supervisor')),
            ],
            options={
                'verbose_name': 'Internship Placement',
                'verbose_name_plural': 'Internship Placements',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Score (0-100)')),
                ('comments', models.TextField(blank=True, verbose_name='Evaluator Comments')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(limit_choices_to={'role__in': ['workplace_supervisor', 'academic_supervisor', 'internship_administrator']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Evaluator')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.evaluationcriteria', verbose_name='Evaluation Criteria')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.internshipplacement', verbose_name='Internship Placement')),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluations',
            },
        ),
        migrations.CreateModel(
            name='WeeklyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField(verbose_name='Week Number')),
                ('activities', models.TextField(verbose_name='Activities Performed')),
                ('achievements', models.TextField(blank=True, verbose_name='Key Achievements')),
                ('challenges', models.TextField(blank=True, verbose_name='Challenges Faced')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='draft', max_length=20, verbose_name='Log Status')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submission Timestamp')),
                ('review_comments', models.TextField(blank=True, verbose_name='Supervisor Review Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_logs', to='core.internshipplacement', verbose_name='Internship Placement')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['workplace_supervisor', 'academic_supervisor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
            options={
                'verbose_name': 'Weekly Log',
                'verbose_name_plural': 'Weekly Logs',
            },
        ),
        migrations.AddConstraint(
            model_name='internshipplacement',
            constraint=models.UniqueConstraint(fields=('student', 'start_date', 'end_date'), name='unique_student_placement_dates'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('placement', 'evaluator', 'criteria')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklylog',
            unique_together={('placement', 'week_number')},
        ),
    ]
